version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run:
          name: gradleDependencies
          command: ./gradlew --stacktrace --console=plain resolveDependencies
      - run:
          name: build
          command: ./gradlew --stacktrace --console=plain assemble
      - run:
          name: test
          command: ./gradlew --stacktrace --console=plain test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
